language: python
cache: pip
python:
  - "2.7"
  - "3.4"
  - "3.6"

services:
  - postgres

before_install:
  - pip install codecov
  - pip install -q psycopg2

install:
  - pip install -e git+https://github.com/modoboa/modoboa#egg=modoboa
  - pip install -q factory-boy testfixtures
  - python setup.py -q develop

before_script:
  - psql -c 'create database modoboa_test;' -U postgres

script:
  - cd test_project
  - coverage run --source ../modoboa_sievefilters manage.py test modoboa_sievefilters

after_success:
  - codecov

before_deploy:
  - cd ../modoboa_sievefilters
  - django-admin compilemessages
  - cd ..

deploy:
  provider: pypi
  user: tonio
  secure:
    secure: "HuXihWm1prcTHTDP37Mruf0hUqWSW3l38t3zQ94t6rchjnLU3J8H0G6nnonhrmHCVpbfgx04vvTS12kr38XgBDCi2ADh7ET5wxTkFoPCuLnoELSPWXNeVvLZmVOzrbjIb76pzAzI/wTOhVsJtrmKBY1mhMqadq4OUz/gWZaB2sE="
  skip_cleanup: true
  on:
    tags: true
    python: '3.6'
